/* It had generated by DirectStruct v1.11.0 */
#include "IDL_hello_world.dsc.h"

static int		_DSC_errline = 0 ;

int DSCINIT_hello_world( hello_world *pst )
{
	int	index[10] = { 0 } ;
	index[0]++; index[0] = 0 ;
	memset( pst , 0x00 , sizeof(hello_world) );
	return 0;
}

int DSCNETORDER_hello_world( hello_world *pst )
{
	int	index[10] = { 0 } ;
	index[0]++; index[0] = 0 ;
	return 0;
}

int DSCHOSTORDER_hello_world( hello_world *pst )
{
	int	index[10] = { 0 } ;
	index[0]++; index[0] = 0 ;
	return 0;
}

int DSCSERIALIZE_COMPRESS_hello_world( hello_world *pst , char *buf , int *p_len )
{
	char	*ptr = buf ;
	int	len = 0 ;
	int	index[10] = { 0 } ;
	index[0]++; index[0] = 0 ;
	/* message */
	{
	unsigned int size=strlen(pst->message);
	COMPRESS_UINT4( size , ptr , len )
	memcpy( ptr , pst->message , size );
	len+=size; ptr+=size;
	}
	
	if( p_len ) (*p_len) = len ;
	
	return 0;
}

int DSCDESERIALIZE_COMPRESS_hello_world( char *buf , int *p_len , hello_world *pst )
{
	char	*ptr = buf ;
	int	len = 0 ;
	int	index[10] = { 0 } ;
	index[0]++; index[0] = 0 ;
	/* message */
	{
	unsigned int size ;
	UNCOMPRESS_UINT4( ptr , len , size )
	memcpy( pst->message , ptr , size );
	len+=size; ptr+=size;
	}
	
	if( p_len ) (*p_len) = len ;
	
	return 0;
}
int DSCGetErrorLine_hello_world()
{
	return _DSC_errline;
}

